vtk_module(vtkDomainsMicroscopy
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkIOImage
  PRIVATE_DEPENDS
    vtkIOXML
    vtkFiltersSources
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionImage
    vtkRenderingContext${VTK_RENDERING_BACKEND}
  EXCLUDE_FROM_ALL
  )
